"""empty message

Revision ID: 0c40af5f4a5e
Revises: 3d1b1ab79aa0
Create Date: 2021-04-01 11:45:06.463523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c40af5f4a5e'
down_revision = '3d1b1ab79aa0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('EVENTS', sa.Column('id_base_event', sa.Integer(), nullable=False))
    op.add_column('EVENTS', sa.Column('id_base_user', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('EVENTS', 'id_base_user')
    op.drop_column('EVENTS', 'id_base_event')
    # ### end Alembic commands ###
