"""add rank table:

Revision ID: 1532af8b59e6
Revises: 017d42dd415b
Create Date: 2021-03-18 01:47:08.149562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1532af8b59e6'
down_revision = '017d42dd415b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('RankTable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('RankID', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('name_full', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('RankID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('RankTable')
    # ### end Alembic commands ###
