"""empty message

Revision ID: 1c6bdf76963b
Revises: c758347ec0ea
Create Date: 2021-03-26 00:12:51.391815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c6bdf76963b'
down_revision = 'c758347ec0ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('EventsData', sa.Column('reached_rank_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('EventsData', 'reached_rank_id')
    # ### end Alembic commands ###
