"""add sex and other

Revision ID: 1f169698c3e2
Revises: 44d99b2ae740
Create Date: 2021-03-13 18:45:31.719485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f169698c3e2'
down_revision = '44d99b2ae740'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SexTable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('name_full', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('BaseTable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('gun_name', sa.String(), nullable=False),
    sa.Column('caption', sa.String(), nullable=False),
    sa.Column('measure', sa.String(), nullable=False),
    sa.Column('rank', sa.String(), nullable=False),
    sa.Column('id_sex', sa.Integer(), nullable=False),
    sa.Column('number_shoot', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_sex'], ['SexTable.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('BaseTable')
    op.drop_table('SexTable')
    # ### end Alembic commands ###
