"""flask security next

Revision ID: 2fc0b8320890
Revises: a69d6f243c41
Create Date: 2021-03-27 01:08:33.418966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fc0b8320890'
down_revision = 'a69d6f243c41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('USERS', 'date_user_made',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('USERS', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('USERS', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('USERS', 'date_user_made',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
