"""empty message

Revision ID: 3d1b1ab79aa0
Revises: 111ad4af979d
Create Date: 2021-03-28 23:18:02.608963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d1b1ab79aa0'
down_revision = '111ad4af979d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('EVENTS', sa.Column('end_date', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('EVENTS', 'end_date')
    # ### end Alembic commands ###
