"""remake relationship user-events

Revision ID: 4110d9271ed4
Revises: f2308ec31173
Create Date: 2021-03-09 17:20:55.915071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4110d9271ed4'
down_revision = 'f2308ec31173'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('EVENTS_user_id_fkey', 'EVENTS', type_='foreignkey')
    op.create_foreign_key(None, 'EVENTS', 'USERS', ['id_user'], ['id'])
    op.drop_column('EVENTS', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('EVENTS', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'EVENTS', type_='foreignkey')
    op.create_foreign_key('EVENTS_user_id_fkey', 'EVENTS', 'USERS', ['user_id'], ['id'])
    # ### end Alembic commands ###
