"""add sex and other

Revision ID: 44d99b2ae740
Revises: dd2c6c20cf7f
Create Date: 2021-03-13 18:31:32.000819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44d99b2ae740'
down_revision = 'dd2c6c20cf7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('EventsData', sa.Column('city_player', sa.String(), nullable=False))
    op.add_column('EventsData', sa.Column('organization_player', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('EventsData', 'organization_player')
    op.drop_column('EventsData', 'city_player')
    # ### end Alembic commands ###
