"""add role events

Revision ID: 4bfa4fff31fc
Revises: 45e04289698b
Create Date: 2021-04-11 16:47:31.131967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bfa4fff31fc'
down_revision = '45e04289698b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('RoleEvents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_event', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_event'], ['EVENTS.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['USERS.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('RoleEvents')
    # ### end Alembic commands ###
