"""update base table

Revision ID: 54efef3ec42e
Revises: dc9c38b8a34b
Create Date: 2021-03-14 16:05:22.602198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54efef3ec42e'
down_revision = 'dc9c38b8a34b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('BaseTable', sa.Column('value', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('BaseTable', 'value')
    # ### end Alembic commands ###
