"""add role events

Revision ID: 631a9fb850b5
Revises: 662ab30ddc05
Create Date: 2021-04-11 16:57:01.719250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '631a9fb850b5'
down_revision = '662ab30ddc05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('RoleEvents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_event', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_event'], ['EVENTS.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['USERS.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('RoleEvents')
    # ### end Alembic commands ###
