"""empty message

Revision ID: 708c17369e01
Revises: a0f02a0b0af0
Create Date: 2021-03-21 18:43:46.108526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '708c17369e01'
down_revision = 'a0f02a0b0af0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Exercise', sa.Column('caption', sa.String(), nullable=False))
    op.add_column('Exercise', sa.Column('distance1', sa.Integer(), nullable=False))
    op.add_column('Exercise', sa.Column('distance2', sa.Integer(), nullable=False))
    op.add_column('Exercise', sa.Column('first_f', sa.Integer(), nullable=False))
    op.add_column('Exercise', sa.Column('first_m', sa.Integer(), nullable=False))
    op.add_column('Exercise', sa.Column('kms_f', sa.Integer(), nullable=False))
    op.add_column('Exercise', sa.Column('kms_m', sa.Integer(), nullable=False))
    op.add_column('Exercise', sa.Column('measure', sa.String(), nullable=False))
    op.add_column('Exercise', sa.Column('ms_f', sa.Integer(), nullable=False))
    op.add_column('Exercise', sa.Column('ms_m', sa.Integer(), nullable=False))
    op.add_column('Exercise', sa.Column('msmk_f', sa.Integer(), nullable=False))
    op.add_column('Exercise', sa.Column('msmk_m', sa.Integer(), nullable=False))
    op.add_column('Exercise', sa.Column('name_gun', sa.String(), nullable=False))
    op.add_column('Exercise', sa.Column('second_f', sa.Integer(), nullable=False))
    op.add_column('Exercise', sa.Column('second_m', sa.Integer(), nullable=False))
    op.add_column('Exercise', sa.Column('third_f', sa.Integer(), nullable=False))
    op.add_column('Exercise', sa.Column('third_m', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Exercise', 'third_m')
    op.drop_column('Exercise', 'third_f')
    op.drop_column('Exercise', 'second_m')
    op.drop_column('Exercise', 'second_f')
    op.drop_column('Exercise', 'name_gun')
    op.drop_column('Exercise', 'msmk_m')
    op.drop_column('Exercise', 'msmk_f')
    op.drop_column('Exercise', 'ms_m')
    op.drop_column('Exercise', 'ms_f')
    op.drop_column('Exercise', 'measure')
    op.drop_column('Exercise', 'kms_m')
    op.drop_column('Exercise', 'kms_f')
    op.drop_column('Exercise', 'first_m')
    op.drop_column('Exercise', 'first_f')
    op.drop_column('Exercise', 'distance2')
    op.drop_column('Exercise', 'distance1')
    op.drop_column('Exercise', 'caption')
    # ### end Alembic commands ###
