"""add relationship RankTable

Revision ID: a0f02a0b0af0
Revises: 1532af8b59e6
Create Date: 2021-03-18 15:33:04.588179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0f02a0b0af0'
down_revision = '1532af8b59e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('EventsData', sa.Column('RankID', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'EventsData', 'RankTable', ['RankID'], ['RankID'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'EventsData', type_='foreignkey')
    op.drop_column('EventsData', 'RankID')
    # ### end Alembic commands ###
