"""flask security

Revision ID: a69d6f243c41
Revises: 1888d0caf41d
Create Date: 2021-03-27 01:07:00.466702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a69d6f243c41'
down_revision = '1888d0caf41d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('USERS', 'login',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('USERS', 'login',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
