"""empty message

Revision ID: c758347ec0ea
Revises: 2f69f7ebc55c
Create Date: 2021-03-26 00:12:12.592741

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c758347ec0ea'
down_revision = '2f69f7ebc55c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('EventsData', 'reached_rank_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('EventsData', sa.Column('reached_rank_id', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
