"""update base table

Revision ID: dc9c38b8a34b
Revises: d3621caca0d6
Create Date: 2021-03-14 16:04:22.577186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc9c38b8a34b'
down_revision = 'd3621caca0d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('BaseTable', 'value')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('BaseTable', sa.Column('value', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
