"""empty message

Revision ID: e3e2ebd772fb
Revises: 6372e68e61ce
Create Date: 2021-03-26 00:36:52.309167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3e2ebd772fb'
down_revision = '6372e68e61ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('EventsData', sa.Column('reached_rank', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('EventsData', 'reached_rank')
    # ### end Alembic commands ###
