"""next update

Revision ID: ebe62e210240
Revises: 3859852f6dbb
Create Date: 2021-03-16 23:47:53.320542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebe62e210240'
down_revision = '3859852f6dbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('EventsData_ExerciseID_fkey', 'EventsData', type_='foreignkey')
    op.create_foreign_key(None, 'EventsData', 'Exercise', ['ExerciseID'], ['ExerciseID'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'EventsData', type_='foreignkey')
    op.create_foreign_key('EventsData_ExerciseID_fkey', 'EventsData', 'Exercise', ['ExerciseID'], ['id'])
    # ### end Alembic commands ###
