"""add relationship

Revision ID: f2308ec31173
Revises: e72a669fa934
Create Date: 2021-03-08 16:04:19.111186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2308ec31173'
down_revision = 'e72a669fa934'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('EVENTS', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'EVENTS', 'USERS', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'EVENTS', type_='foreignkey')
    op.drop_column('EVENTS', 'user_id')
    # ### end Alembic commands ###
