"""empty message

Revision ID: f2f4de149d2f
Revises: a503ba6c04bb
Create Date: 2020-12-29 13:30:56.385201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2f4de149d2f'
down_revision = 'a503ba6c04bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('USERS', sa.Column('date_user_made', sa.String(), nullable=False))
    op.add_column('USERS', sa.Column('password_hash', sa.String(), nullable=False))
    op.alter_column('USERS', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('USERS', 'login',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'USERS', ['login'])
    op.create_unique_constraint(None, 'USERS', ['email'])
    op.drop_column('USERS', 'key_pass')
    op.drop_column('USERS', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('USERS', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('USERS', sa.Column('key_pass', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'USERS', type_='unique')
    op.drop_constraint(None, 'USERS', type_='unique')
    op.alter_column('USERS', 'login',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('USERS', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('USERS', 'password_hash')
    op.drop_column('USERS', 'date_user_made')
    # ### end Alembic commands ###
